.TH ELEV 1 "2026-04-20" "1.0.0" "elev Manual"
.SH NAME
elev \- execute a command as another user
.SH SYNOPSIS
.B elev
[\fB\-h\fR] [\fB\-v\fR] [\fB\-k\fR] [\fB\-u\fR \fIuser\fR] \fIcommand\fR [\fIargument\fR ...]
.SH DESCRIPTION
.B elev
allows a permitted user to execute a
.I command
as another user, as specified by the configuration file
.IR /etc/elev/conf .
By default, the command is executed as the superuser (root).
.PP
The execution environment is strictly sanitized for security. All environment 
variables are cleared except for \fBTERM\fR, which is preserved if it exists. 
The \fBPATH\fR variable is reset to a safe default value:
.IP
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
.PP
Users may be required to authenticate themselves via PAM before the command is 
executed, depending on the policy. Authentication can be cached using the 
\fBpersist\fR option (see \fBelev\fR(5)).
Persistence is only reused for invocations attached to a real TTY; non-TTY
invocations always require fresh authentication.
Cached authentication is scoped to the target user, matched rule, and command
line.
.PP
The parent process keeps the PAM session open while the target command runs and
closes it after the command exits.

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Display a short help message and exit.
.TP
.BR \-k ", " \-\-reset\-timestamp
Invalidate the user's cached credentials (reset the persistence timestamp). 
If no command is specified, \fBelev\fR will exit after resetting the timestamp. 
This is equivalent to \fBsudo -k\fR.
.TP
.BR \-u " \fIuser\fR"
Execute the command as the specified \fIuser\fR instead of \fBroot\fR.
The \fIuser\fR can be a login name or a numeric user ID (UID).
.TP
.BR \-v ", " \-\-version
Print version information and exit.

.SH EXIT STATUS
Upon successful execution, the exit status of \fBelev\fR will be the exit 
status of the executed command.
.PP
If \fBelev\fR fails to execute the command due to an internal error, a 
configuration mismatch, or an authentication failure, it exits with a 
value of 1.

.SH EXAMPLES
To run an interactive shell as root:
.IP
$ elev /bin/sh
.PP
To list the contents of a directory as the \fBwww-data\fR user:
.IP
$ elev -u www-data /usr/bin/ls /var/www
.PP
To update the system (requires appropriate rules in \fBelev.conf\fR):
.IP
$ elev /usr/bin/apt update

.SH FILES
.TP
.I /etc/elev/conf
Policy configuration file.
.TP
.I /etc/pam.d/elev
PAM configuration file. A default profile is installed with
.BR make\ install ,
but systems without a
.B system-auth
stack may need local adjustments.
.TP
.I /run/elev/
Directory used for authentication persistence timestamps.

.SH SEE ALSO
.BR elev (5),
.BR elev (7),
.BR pam (8)

.SH AUTHORS
.B elev
was written by pdlayer.
